//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interlocking_BatterySaver_by_Wi_Fi_.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Interlocking_BatterySaver_by_Wi_Fi_.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ___ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ___ {
            get {
                return ResourceManager.GetString("___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Wi-Fi Access Point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Add_AP {
            get {
                return ResourceManager.GetString("Add_AP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Wi-Fi Access Point (AP) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddWifiAPDialogTitleName {
            get {
                return ResourceManager.GetString("AddWifiAPDialogTitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Always {
            get {
                return ResourceManager.GetString("Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AP Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AP_Name {
            get {
                return ResourceManager.GetString("AP_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duplicate access point name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AP_name_duplicated {
            get {
                return ResourceManager.GetString("AP_name_duplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimize app に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppMinimize {
            get {
                return ResourceManager.GetString("AppMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Battery (%) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Battery__ {
            get {
                return ResourceManager.GetString("Battery__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current AP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Current_AP {
            get {
                return ResourceManager.GetString("Current_AP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GitHub に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid AP name is set. Please reconfirm. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Invalid_AP_name_is_set___ {
            get {
                return ResourceManager.GetString("Invalid_AP_name_is_set___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Closing a window when operating another window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Prefs_DeactivatedWindowClose {
            get {
                return ResourceManager.GetString("Prefs_DeactivatedWindowClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pre-load the main window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Prefs_MainWindowPrefetch {
            get {
                return ResourceManager.GetString("Prefs_MainWindowPrefetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resource Check に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceCheck {
            get {
                return ResourceManager.GetString("ResourceCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App Name: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceCheck_AppPackage_Script_Target_Name_Title {
            get {
                return ResourceManager.GetString("ResourceCheck_AppPackage_Script_Target_Name_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Script Version: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceCheck_AppPackage_Script_Ver {
            get {
                return ResourceManager.GetString("ResourceCheck_AppPackage_Script_Ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application Package Identification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceCheck_AppPackage_Title {
            get {
                return ResourceManager.GetString("ResourceCheck_AppPackage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceCheck_Failed {
            get {
                return ResourceManager.GetString("ResourceCheck_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceCheck_Loading {
            get {
                return ResourceManager.GetString("ResourceCheck_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Healthy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceCheck_Success {
            get {
                return ResourceManager.GetString("ResourceCheck_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access point added to list. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SNACKBAR_AddCompleted {
            get {
                return ResourceManager.GetString("SNACKBAR_AddCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Addition Complete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SNACKBAR_AddCompletedTitle {
            get {
                return ResourceManager.GetString("SNACKBAR_AddCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access point removed from list. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SNACKBAR_DeleteCompleted {
            get {
                return ResourceManager.GetString("SNACKBAR_DeleteCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deletion complete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SNACKBAR_DeleteCompletedTitle {
            get {
                return ResourceManager.GetString("SNACKBAR_DeleteCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updated access point settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SNACKBAR_UpdateCompleted {
            get {
                return ResourceManager.GetString("SNACKBAR_UpdateCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SNACKBAR_UpdateCompletedTitle {
            get {
                return ResourceManager.GetString("SNACKBAR_UpdateCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The initial startup process will begin. After pressing &quot;OK,&quot; click on the icon in the lower right status bar to begin the setup. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartupReg {
            get {
                return ResourceManager.GetString("StartupReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Microsoft Store に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interlocking BatterySaver by Wi-Fi  v2.2.2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SYSTEM_APP_TITLE {
            get {
                return ResourceManager.GetString("SYSTEM_APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   © 2023 taksas に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SYSTEM_DEVELOPER {
            get {
                return ResourceManager.GetString("SYSTEM_DEVELOPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add a new access point to the list. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TOOLTIP_AddAccessPoint {
            get {
                return ResourceManager.GetString("TOOLTIP_AddAccessPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add access points with the above conditions. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TOOLTIP_AddAP_Add {
            get {
                return ResourceManager.GetString("TOOLTIP_AddAP_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancels the addition of the access point. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TOOLTIP_AddAP_Cancel {
            get {
                return ResourceManager.GetString("TOOLTIP_AddAP_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retrieves the current access point from the system; may take up to 5 seconds. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TOOLTIP_AddAP_CurrentAP {
            get {
                return ResourceManager.GetString("TOOLTIP_AddAP_CurrentAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit the application and deactivate the resident application. If you want to keep the application resident without closing it, tap anywhere other than the application window. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TOOLTIP_AppExit {
            get {
                return ResourceManager.GetString("TOOLTIP_AppExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimizes the application and returns it to the taskbar. This button will appear if you have set the window not to close automatically from the settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TOOLTIP_AppMinimize {
            get {
                return ResourceManager.GetString("TOOLTIP_AppMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deletes the selected battery saver rule. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TOOLTIP_ListDelete {
            get {
                return ResourceManager.GetString("TOOLTIP_ListDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change the threshold of the power saving mode rule to the selected value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TOOLTIP_ListUpdate {
            get {
                return ResourceManager.GetString("TOOLTIP_ListUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Menu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TOOLTIP_More {
            get {
                return ResourceManager.GetString("TOOLTIP_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open GitHub Page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TOOLTIP_OpenLink_GitHub {
            get {
                return ResourceManager.GetString("TOOLTIP_OpenLink_GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Help Page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TOOLTIP_OpenLink_Help {
            get {
                return ResourceManager.GetString("TOOLTIP_OpenLink_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Store Page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TOOLTIP_OpenLink_Store {
            get {
                return ResourceManager.GetString("TOOLTIP_OpenLink_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select whether or not to automatically close this app&apos;s window when you operate another app&apos;s window. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TOOLTIP_Prefs_DeactivatedWindowClose {
            get {
                return ResourceManager.GetString("TOOLTIP_Prefs_DeactivatedWindowClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The main window is preloaded to speed up startup. Memory usage will increase by 10MB or more while resident. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TOOLTIP_Prefs_MainWindowPrefetch {
            get {
                return ResourceManager.GetString("TOOLTIP_Prefs_MainWindowPrefetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close the Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TOOLTIP_Window_Close {
            get {
                return ResourceManager.GetString("TOOLTIP_Window_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Currently applied settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Triggered_Wifi_Title {
            get {
                return ResourceManager.GetString("Triggered_Wifi_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turn battery saver on automatically at : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Turn_battery_saver_on_AM_at__ {
            get {
                return ResourceManager.GetString("Turn_battery_saver_on_AM_at__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When connected to other Wi-Fi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string When_connected_to_other_WiFi {
            get {
                return ResourceManager.GetString("When_connected_to_other_WiFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When not connected to Wi-Fi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string When_not_connected_to_WiFi {
            get {
                return ResourceManager.GetString("When_not_connected_to_WiFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wi-Fi AP : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Wi_Fi_AP_ {
            get {
                return ResourceManager.GetString("Wi-Fi_AP_", resourceCulture);
            }
        }
    }
}
