//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interlocking_BatterySaver_by_Wi_Fi_.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Interlocking_BatterySaver_by_Wi_Fi_.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ___ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ___ {
            get {
                return ResourceManager.GetString("___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Wi-Fi Access Point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Add_AP {
            get {
                return ResourceManager.GetString("Add_AP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Wi-Fi Access Point (AP) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddWifiAPDialogTitleName {
            get {
                return ResourceManager.GetString("AddWifiAPDialogTitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Always {
            get {
                return ResourceManager.GetString("Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AP Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AP_Name {
            get {
                return ResourceManager.GetString("AP_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Battery (%) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Battery__ {
            get {
                return ResourceManager.GetString("Battery__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current AP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Current_AP {
            get {
                return ResourceManager.GetString("Current_AP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Terminate App に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExitApp {
            get {
                return ResourceManager.GetString("ExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid AP name is set. Please reconfirm. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Invalid_AP_name_is_set___ {
            get {
                return ResourceManager.GetString("Invalid_AP_name_is_set___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The initial startup process will begin. After pressing &quot;OK,&quot; click on the icon in the lower right status bar to begin the setup. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartupReg {
            get {
                return ResourceManager.GetString("StartupReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interlocking BatterySaver by Wi-Fi    Ver1.2.1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SYSTEM_APP_TITLE {
            get {
                return ResourceManager.GetString("SYSTEM_APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turn battery saver on automatically at : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Turn_battery_saver_on_AM_at__ {
            get {
                return ResourceManager.GetString("Turn_battery_saver_on_AM_at__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When connected to other Wi-Fi : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string When_connected_to_other_WiFi {
            get {
                return ResourceManager.GetString("When_connected_to_other_WiFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When not connected to Wi-Fi : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string When_not_connected_to_WiFi {
            get {
                return ResourceManager.GetString("When_not_connected_to_WiFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wi-Fi AP : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Wi_Fi_AP_ {
            get {
                return ResourceManager.GetString("Wi-Fi_AP_", resourceCulture);
            }
        }
    }
}
